In [43]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

 Think of all data fundamentally as arrays of numbers.

In [1]:
import numpy as np

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible

In [6]:
np.array([3.14, 4, 2, 3]) # integers are up-cast to floating point

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size = 6) # One-dimensional array
x2 = np.random.randint(10, size = (3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # Three-dimensional array

Each array has three attributes:
1. `ndim`: number of dimensions
2. `shape`: size of each dimension
3. `size`: total size of the array

In [13]:
print(f"x3 ndim: {x3.ndim}")
print(f"x3 shape: {x3.shape}")
print(f"x3 size: {x3.size}")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [14]:
print(f"dtype: {x3.dtype}")

dtype: int64


In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

NumPy slicing syntax follows the standard Python list:
`x[start = 0:stop = size of dimension:step = 1]`

In [27]:
x = np.arange(10)
x[::2]
x[1::2]

array([0, 2, 4, 6, 8])

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [29]:
x # original
x[::-1] # all elements are reversed
x[5::-2] # reversed every other from index 5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([5, 3, 1])

Multi-dimensional slices work in the same way, with multiple slices separated by commas.

In [30]:
x2
x2[:2, :3] # two rows, three columns
x2[:3, ::2] # three rows, every other column

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[3, 5, 2],
       [7, 6, 8]])

array([[3, 2],
       [7, 8],
       [1, 7]])

In [31]:
x2
x2[::-1, ::-1]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

Access single rows or columns of an array by combining indexing and slicing.

In [40]:
x2
x2[:, 0]
x2[:, 0:2]
x2[0, :]
x2[0]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([3, 7, 1])

array([[3, 5],
       [7, 6],
       [1, 6]])

array([3, 5, 2, 4])

array([3, 5, 2, 4])

Array slices return *views* rather than copies of array data. If we modify a subarray the original is also modified

In [48]:
x2
x2_sub = x2[:2, :2]
x2_sub
x2_sub[0, 0] = 99
x2_sub
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[3, 5],
       [7, 6]])

array([[99,  5],
       [ 7,  6]])

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Copy the data within an array with the `copy()` method, this will avoid modifying the original array

In [50]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy
x2_sub_copy[0, 0] = 42
x2_sub_copy
x2

array([[99,  5],
       [ 7,  6]])

array([[42,  5],
       [ 7,  6]])

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
grid = np.arange(1, 10)
grid
grid.reshape((3,3))
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x = np.array([1, 2, 3])
x
x.reshape((1, 3))
x.reshape((3, 1))

array([1, 2, 3])

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])